new

diff --git a/cairo1/scripts/cairo-make-commands b/cairo1/scripts/cairo-make-commands
--- a/cairo1/scripts/cairo-make-commands
+++ b/cairo1/scripts/cairo-make-commands
@@ -4,33 +4,31 @@ cairo-watch-header
 
 # Function to execute commands and handle errors
 execute_command() {
-	output=$(eval "make compile" 2>&1)
-	status=$?
-	if [ $status -ne 0 ]; then
-		# I dont want to see all errors
-		echo -e "\033[31mCOMPILATION ERROR\033[0m"
-		echo "$output" | head -n 15
-		exit 1
-	else
-		# Command exited successfully
-		echo -e "\033[32mCOMPILATION OK\033[0m"
-	fi
 	command="$1"
 	debug_print=$2
 	output=$(eval "$command" 2>&1)
 	status=$?
 	# Error
 	if [ $status -ne 0 ]; then
-		echo -e "\033[31mTESTING ERROR\033[0m"
 		if [ $debug_print -eq 1 ]; then
 			# Need to see all errors
 			echo "$output"
 		else
-			output=$(echo "$output" | awk '/failures:/,/make: \*\*\* .* Error/')
-			if [[ -z "$output" ]]; then
-				echo -e "Passed some wrong arguments. Allowed \n --debug-print"
+			# Error: failed to compile:
+			test_fail=$(echo "$output" | awk '/failures:/')
+			compile_fail=$(echo "$output" | awk '/Error: failed to compile:/')
+			if [[ -n "$compile_fail" ]]; then
+				# I dont want to see all errors
+				echo -e "\033[31mCOMPILATION ERROR\033[0m"
+				echo "$output" | head -n 15
+				exit 1
+			elif [[ -n "$test_fail" ]]; then
+				# I dont want to see all errors
+				echo -e "\033[31mTESTING ERROR\033[0m"
+				result=$(echo "$output" | awk '/failures:/,/make: \*\*\* .* Error/')
+				echo "$result"
 			else
-				echo "$output"
+				echo -e "Something Failed. Maybe passed some wrong arguments. Allowed \n --debug-print"
 			fi
 
 		fi
@@ -47,6 +45,7 @@ execute_command() {
 
 filtered_args=()
 should_debug_print=0
+starknet_project=0
 for arg in "$@"; do
 	if [ "$arg" != '--debug-print' ]; then
 		filtered_args+=("$arg")
diff --git a/cairo1/scripts/cairo-new b/cairo1/scripts/cairo-new
--- a/cairo1/scripts/cairo-new
+++ b/cairo1/scripts/cairo-new
@@ -1,8 +1,9 @@
 #!/bin/bash
 
+project_names_not_allowed=("test","keccak")
 # Check number of arguments
 if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
-	echo "Usage: cairo-new [--starknet|--polygon] <project-name>"
+	echo "Usage: cairo-new [--starknet] <project-name>"
 	exit 1
 fi
 
@@ -13,10 +14,12 @@ case "$1" in
 			echo "Usage: cairo-new --starknet <project-name>"
 			exit 1
 		fi
-		if [ "$2" == "test" ]; then
-			echo "Error: Do not name the project as 'test'."
-			exit 1
-		fi
+		for element in "${project_names_not_allowed[@]}"; do
+			if [[ $2 == $element ]]; then
+				echo "Error: Do not name the project as 'test'."
+				exit 1
+			fi
+		done
 		echo "Executing for Starknet Project..."
 		# Use the command with --starknet here, "$2" will be the <project-name>
 		starknet-new $2
